### ISSUE TITLE
Disable ZRAM does not work

### ISSUE THREAD

**Issue by crok** [Magisk-Modules-Repo/zram_config#1]
Hi,

Disabling ZRAM does not work. When installing the module asks me to press vol key according to my decision, I want to disable ZRAM, then restarted the device, tried several times (uninstall + install again), nothing changes: ZRAM is still on, the module seems to does nothing.
Probably the difference between the disable_swap and enable_swap is the root cause of the issue?

The definition of zram_dev variable is different in the disable function than in the enable function
and write functions' arguments has quoting in enable function but does not have in disable function:
```
function disable_swap() {

    for zram in blkid | grep swap | awk -F[/:] '{print $4}'; do {
		zram_dev="${zram_dev}"
		dev_index="$( echo $zram | grep -o "[0-9]*$" )"
		write /sys/class/zram-control/hot_remove ${dev_index}
		${swff} ${zram_dev} && zram_reset ${zram}
	} done
```

but

```
function enable_swap() {
...
   for zram in blkid | grep swap | awk -F[/:] '{print $4}'; do {
		zram_dev="/dev/block/${zram}"
		dev_index="$( echo $zram | grep -o "[0-9]*$" )"
		write "/sys/class/zram-control/hot_remove" ${dev_index}
		${swff} ${zram_dev} && zram_reset ${zram}
	} done
```

**Comment by crok** [comment]
@korom42 : Do you plan to fix it or you are abandoning this module?

**Comment by Zandersig** [comment]
Yes. I would also like to know that. I hate BOOTLOOPS and if I install this I want to be able to uninstall it.

Will this module help me play Video games on my Nexus 5? I'm addicted to the game called SKULLGIRLS and I don't have the money for a new phone. It plays good now but there are some slow downs and that is when I loose. 

Will this module improve my gaming? And how do I uninstall it?

If we have to use the volume buttons wouldn't that interfere with booting into TWRP or Recovery?

**Comment by Zandersig** [comment]
Hello? Is the developer ever going to answer my questions?

**Comment by crok** [comment]
> Hello? Is the developer ever going to answer my questions?

It seems not... .. .

**Comment by Zandersig** [comment]
Yep... Thanks anyway brah!

**Comment by crok** [comment]
I am now 100% sure about the above mentioned thing.

In `disable_swap` I changed
`zram_dev="${zram_dev}"`
to
`zram_dev="/dev/block/${zram}"`
then installed the module and it disabled zRAM correctly.

Can you please make this tiny change to happen in the repo?

**Comment by korom42** [comment]
The code has been corrected, thanks to @crok
